CREATE TABLE SUBSCRIBER 
(SubscriberID int NOT NULL AUTO_INCREMENT,
 Email varchar(255) NOT NULL, 
 Name varchar(255),
 NodeID int,
 FOREIGN KEY (NodeID) REFERENCES NODE(NodeID));
 PRIMARY KEY(SubscriberID));